services:
  postgres:
    container_name: camel.postgres
    restart: always
    image: postgres:14-alpine
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    env_file:
      - '.env'
    networks:
      - camel-net
  redis:
    container_name: camel.redis
    restart: always
    image: bitnami/redis:latest
    volumes:
      - ./.data/redis:/bitnami/redis/data
    env_file:
      - '.env'
    networks:
      - camel-net
  nginx:
    container_name: camel.nginx
    restart: always
    image: nginx
    ports:
      - 80:80
      - 443:443
      - 13380:13380
      - 13381:13381
      - 13382:13382
      - 13383:13383
    volumes:
      - ./conf/default.conf:/etc/nginx/templates/default.conf.template
      - ./.data:/.data
    env_file:
      - '.env'
    networks:
      - camel-net
  camel.bancho:
    container_name: camel.bancho
    restart: always
    build:
      context: .
      dockerfile: src/Camel.Bancho/Dockerfile
    env_file:
      - '.env'
    volumes:
      - ./.data:/.data
      - ./bin:/.bin
    networks:
      - camel-net
  camel.web:
    container_name: camel.web
    restart: always
    build:
      context: .
      dockerfile: src/Camel.Web/Dockerfile
    env_file:
      - '.env'
    volumes:
      - ./.data:/.data
    networks:
      - camel-net

networks:
  camel-net: