services:
  postgres:
    restart: always
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=camel_user
      - POSTGRES_DB=camel_db
  nginx:
    restart: always
    image: nginx:1-alpine
    ports:
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - camel.webapi
  camel.webapi:
    image: camel.webapi
    build:
      context: .
      dockerfile: src/Camel.WebApi/Dockerfile
  camel.web:
    image: camel.web
    build:
      context: .
      dockerfile: src/Camel.Web/Dockerfile
